PY=python3

keygen:
	$(PY) keygen.py

keygen-tests:
	$(PY) keygen_tests.py

aem:
	$(PY) aem.py

aem-tests:
	$(PY) aem_tests.py

rpi:
	$(PY) rpi.py

rpi-tests:
	$(PY) rpi_tests.py

tests:
	$(PY) keygen_tests.py
	$(PY) aem_tests.py
	$(PY) rpi_tests.py

